name: Cleanup 🧼

on:
  delete:
  workflow_dispatch:


jobs:

  cleanup-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      - name: Remove unused builds 🗑
        run: sh remove-unused-builds.sh

      - name: Apply Changes cleanup 🚀
        run: |
          git commit -m "Cleanup 🧼"
          git push origin gh-pages