name: Build and Deploy
on:
  workflow_dispatch:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!prod'   # excludes master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cat << EOF > ./src/config.json
          {
            "apiKey": "${{secrets.API_KEY}}",
            "authDomain": "${{secrets.AUTH_DOMAIN}}",
            "databaseURL": "${{secrets.DATABASE_URL}}",
            "projectId": "${{secrets.PROJECT_ID}}",
            "storageBucket": "${{secrets.STORAGE_BUCKET}}",
            "messagingSenderId": "${{secrets.MESSAGING_SENDER_ID}}",
            "appId": "${{secrets.APP_ID}}",
            "measurementId": "${{secrets.MEASUREMENT_ID}}"        
          }
          EOF
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          branch: gh-pages
